name: Release
on:
  workflow_dispatch:
    inputs:
      nextVersion:
        description: 'Next development version without "SNAPSHOT". If not provided, the next version will be calculated from the pom'
        required: false
        type: string

jobs:
  pre-release:
    uses: gluonhq/actions/.github/workflows/maven-pre-release.yml@v1
    with:
      buildDir: emoji
      depProperty: emoji.version
      depDirectory: samples

  release:
    needs: pre-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Publish Release
        id: deploy
        run: |
          mvn -B -ntp clean deploy -f emoji -Prelease
          echo ::set-output name=exit_code::$?
        env:
          MAVEN_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          MAVEN_CENTRAL_TOKEN: ${{ secrets.SONATYPE_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

  post-release:
    needs: [ pre-release, release ]
    uses: gluonhq/actions/.github/workflows/maven-post-release.yml@v1
    with:
      tag: ${{ needs.pre-release.outputs.tag }}
      nextVersion: ${{ github.event.inputs.nextVersion }}
      buildDir: emoji
      depProperty: emoji.version
      depDirectory: samples
